# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teleport.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 989)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.dirTree = QtWidgets.QTreeView(self.centralwidget)
        self.dirTree.setMinimumSize(QtCore.QSize(50, 0))
        self.dirTree.setSizeIncrement(QtCore.QSize(50, 0))
        self.dirTree.setBaseSize(QtCore.QSize(50, 0))
        self.dirTree.setMouseTracking(False)
        self.dirTree.setObjectName("dirTree")
        self.gridLayout.addWidget(self.dirTree, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.reload = QtWidgets.QPushButton(self.centralwidget)
        self.reload.setObjectName("reload")
        self.horizontalLayout.addWidget(self.reload)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.fav = QtWidgets.QPushButton(self.centralwidget)
        self.fav.setObjectName("fav")
        self.horizontalLayout.addWidget(self.fav)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.url = QtWidgets.QLabel(self.centralwidget)
        self.url.setObjectName("url")
        self.horizontalLayout_3.addWidget(self.url)
        self.urlEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlEdit.setObjectName("urlEdit")
        self.horizontalLayout_3.addWidget(self.urlEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.webView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webView.setObjectName("webView")

        initurl = "https://www.google.co.jp"
        self.webView.setUrl(QtCore.QUrl(initurl))

        self.verticalLayout.addWidget(self.webView)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 34)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.back.clicked.connect(self.webView.back)
        self.next.clicked.connect(self.webView.forward)
        self.reload.clicked.connect(self.webView.reload)
        self.urlEdit.returnPressed.connect(MainWindow.webPageUpdate)
        self.webView.urlChanged['QUrl'].connect(MainWindow.urlLineSet)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back.setText(_translate("MainWindow", "back"))
        self.next.setText(_translate("MainWindow", "next"))
        self.reload.setText(_translate("MainWindow", "reload"))
        self.fav.setText(_translate("MainWindow", "fav"))
        self.url.setText(_translate("MainWindow", "URL:"))
from PyQt5 import QtWebEngineWidgets
